name: Build premake-core
run-name: Build premake-core for ${{ inputs.platform }} platfom

on:
  workflow_dispatch:
    inputs:
        platform:
            required: true
            default: all
            type: choice
            options:
                - all
                - macos
                - windows
                - linux

jobs:
    macos:
        if: ${{ inputs.platform == 'macos' || inputs.platform == 'all' }}
        runs-on: macos-latest
        timeout-minutes: 30
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Build
          run: make -f Bootstrap.mak osx
        - name: Upload Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: premake5-macos
            path: |
                bin/release/premake5
                bin/release/libluasocket.dylib